apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: rating-sample
build:
  local:
    push: false
  artifacts:
  - image: eduardofsamaral/restaurant-orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: eduardofsamaral/restaurant-restaurants
    context: restaurants
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
